---
- name: Set an additional servervdi arg to install a single session VDA on a multi session OS
  set_fact:
    vda_installer_arguments: "{{ vda_installer_arguments + ' /servervdi' }}"
  when:
    - "'single_session_vda' in ansible_run_tags"
  tags:
    - win_2019_dc_vm
    - win_2022_dc_vm

- name: Set an additional tag to enable Citrix VDA Upgrade Agent
  set_fact:
    vda_installer_arguments: "{{ vda_installer_arguments + ' /includeadditional \"Citrix VDA Upgrade Agent\" ' }}"
  tags: "{{ vda_upgrade_agent_tags }}"

- name: Install MCS VDA
  block:
    - name: Install Citrix VDA on a Windows based Operating system
      win_package:
        path: "{{ vda_installer_path }}"
        arguments: "{{ vda_installer_arguments }}"
        creates_service: BrokerAgent
        state: present
        expected_return_code: [0, 3, 3010]
      register: vda_install

    - name: Reboot the machine
      win_reboot:

    - name: Set retry count
      set_fact:
        retry_count: 0
        max_retries: 3
  when: broker_agent_service_info.exists == false
  tags: "{{ version_exclusive_tags }}"

- name: Check if BrokerAgent service is running
  ansible.windows.win_service_info:
    name: BrokerAgent
  register: broker_agent_service_info
  tags: "{{ version_exclusive_tags }}"

- include_role:
    name: monitor_vda_installation
  when: broker_agent_service_info.exists == false
  tags: "{{ version_exclusive_tags }}"