---
  - name: Download the citrix optimizer folder
    ansible.windows.win_get_url:
      url: "{{ citrix_optimizer_zip_url }}"
      dest: "{{ citrix_optimizer_zip_destination }}"
    tags: always

  - name: Unzip the folder
    win_unzip:
      src: "{{ citrix_optimizer_zip_destination }}"
      dest: "{{ citrix_optimizer_script_destination_folder }}"
      delete_archive: yes
    tags: always

  - name: Run the citrix optimizer script
    ansible.windows.win_powershell: 
      script: "{{ citrix_optimizer_script_path }} {{ citrix_optimizer_script_arguments }}"
      chdir: "{{ citrix_optimizer_script_destination_folder}}"
    register: optimizer_output
    tags: always