---
- name: Test Connection
  win_ping:
  tags: "{{ version_exclusive_tags }}"

- name: Create directory structure to store logs
  ansible.windows.win_file:
    path: C:\Logs
    state: directory
  tags: "{{ version_exclusive_tags }}"

- name: Check if BrokerAgent service is running and set facts
  ansible.windows.win_service_info:
    name: BrokerAgent
  register: broker_agent_service_info
  tags: "{{ version_exclusive_tags }}"